sennetconsortium/ingest-api

src/app.py
src/requirements.txt
src/routes/entity_CRUD/__init__.py
src/routes/entity_CRUD/ingest_file_helper.py

Ceate the /datasets POST endpoint using a Flask blueprint

Initial Flask Blueprint datasets POST endpoint creation

---

src/routes/privs/__init__.py
test_scripts/privs_test.sh

This adds the additional endpoint /privs/user-write-groups as well as contains more protection from throwing errors in the code.

Fix privs routes

---

src/routes/entity_CRUD/__init__.py

lab_id is now a required field for sources

Made lab_id for sources a required field in validation for bulk uploads

---

src/routes/entity_CRUD/__init__.py

Fixed a bug where organ type wasn't properly removed if it was empty

Fixed bug where organ type wasn't properly removed if it was empty

---

src/routes/entity_CRUD/__init__.py

Tweaked regex in validation methods in entity_crud to only allow single 
protocol urls in tsv file.

Tweaked regex in validation methods in entity_crud to only allow single

---

src/routes/entity_CRUD/__init__.py

fixed source type validation for sources being case sensitive when it should not be

fixed source type validation for sources being case sensitive when it

---

src/routes/entity_CRUD/__init__.py

This implements the validation for datasets and samples using the constraints we created. I'm going to need to make one additional tweak to entity api for this to work though.

Derek furst/bulk datasets

---

src/routes/entity_CRUD/__init__.py

Applied earlier fix from datasets to samples. Also applied row_numb 
consistency fixes throughout other validation methods.
Before this, a 404 from uuid api was causing a 500 in ingest api.

Applied earlier fix from datasets to samples. Also applied row_numb

---

src/routes/validation/validation.py

Just add code to remove tsv after usage and dumped the lot of it in a try/catch.

Remove file after upload

---

src/routes/validation/validation.py

Resolved response to use `metadata` field.

Resolve response

---

src/lib/file_upload_helper.py
src/routes/file/__init__.py

1. Use sennet env var instead of hubmap
2. Add /uuid to the uuid-api URL

Add /uuid to the uuid-api URL

---

src/routes/entity_CRUD/__init__.py

Add endpoints `/datasets/<ds_uuid>/file-system-abs-path` and `/entities/<entity_uuid>` needed by airflow pipeline

Add endpoints for airflow pipeline

---

src/routes/entity_CRUD/__init__.py

Change log:
1. Update regex for doi urls

Updated regex to support additional paths in url - #84

---

src/routes/privs/__init__.py

Change log:
1. Add `privs/has-data-admin` endpoint with similar formatting as other endpoints

Add privs_has_data_admin_privs method and endpoint - #599.portal-ui

---

src/routes/entity_CRUD/__init__.py

Change log:
1. Update response formatting

Update response to return obj expected by portal - #138

---

src/routes/entity_CRUD/__init__.py

Change log:
1. Add OT support on validation
Fix for https://github.com/sennetconsortium/entity-api/issues/195

Add support for Other, OT type code

---

src/routes/validation/README.md
src/routes/validation/validation.py

Change log:
1. Add some method comments
2. Add README.md

Add method documentation - #172

---

src/routes/entity_CRUD/__init__.py

Change log:
1.  Add collections_attributes() method

Add simple blueprint collections/attributes to handle TSV uploads - #205

---

src/routes/entity_CRUD/__init__.py

Change log:
1. Use `dataset_is_primary` method

Use dataset_is_primary method - #224

---

ingest-api-spec.yaml
src/routes/vitessce/__init__.py

Changes
- Added basic validation and error handling to Vitessce config endpoint

Adding basic validation and error handling to Vitessce config endpoint

---

src/routes/vitessce/__init__.py

Addresses #274
Changes
- Adding immediate_ancestors to the vitessce config entity

Adding immediate_ancestors to the vitessce config

---

src/lib/rule_chain.py
src/lib/services.py
src/routes/assayclassifier/__init__.py
src/routes/assayclassifier/testing_rule_chain.json
src/routes/vitessce/__init__.py

Addresses #277. This builds upon PR #279.
Changes
- Changed `entity-api` call to `search-api` call in Vitessce config endpoint

Changing `entity-api` call to `search-api` call in Vitessce config endpoint

---

src/routes/entity_CRUD/__init__.py

Change log:
1. Change from using the term derived to processed

Use term processed instead of derived - #300

---

src/routes/entity_CRUD/__init__.py

Change log:
1. Remove `descendant_datasets` query

Removed unused descandant_datasets query - #300

---

src/routes/assayclassifier/testing_rule_chain.json

Addresses #313 
Changes
- Updating the rule chain to the latest version

313 latest rule chain changes

---

src/lib/decorators.py
src/lib/services.py
src/routes/entity_CRUD/__init__.py
src/routes/entity_CRUD/dataset_helper.py
src/routes/entity_CRUD/tasks.py

Still waiting on the ingest-pipeline endpipe. The `submit_dataset` task will fail without the endpoint and set dataset statuses to `Error`.
I've been testing with datasets 
```json
[
"acce52155655b4e5107dab4fd8d5233d",
"b982d78ebffcf1cf1b85db970fc7e5cb"
]
```
Changes
- Added `PUT /datasets/bulk/submit` endpoint
- Added `submit_datasets` background task

Batch dataset submission

---

src/routes/entity_CRUD/tasks.py

This commit fixes a bug where successfully submitted datasets were not updated (task_id, ingest_id) if the ingest-pipeline returned a 200 status code.

Fixing bug where submitted datasets not updated

---

src/jobs/validation.py
src/routes/privs/__init__.py

Change log:
1. Add additional check for other entities like source_id

Add additional check for source_id - #345

---

src/jobs/__init__.py
src/jobs/submission/datasets.py
src/lib/dataset_helper.py
src/lib/ingest_file_helper.py
src/routes/admin/__init__.py
src/routes/entity_CRUD/__init__.py
src/routes/jobs/__init__.py
src/routes/samples/__init__.py
src/routes/sources/__init__.py

Addresses #377, #386 
Changes
- Changed bulk dataset submission to use the job queue.
- Added job visibility (public or private). Public are returned to the end user and private are not.
- Fixed bulk entity validation error message

Bulk dataset submission to job queue

---

src/jobs/validation/metadata.py

Add graceful error for missing source_id - #365

Check that spec is CEDAR

---

src/lib/rule_chain.py
src/routes/assayclassifier/testing_rule_chain.json

Basing this PR off of this commit https://github.com/hubmapconsortium/ingest-api/commit/ba19213edd9b43aa734eba5b744bede23cc49bc1

Porting over latest 'testing_rule_chain' changes

---

src/app.py
src/lib/converters.py
src/lib/dataset_helper.py
src/lib/neo4j_helper.py
src/lib/request_validation.py
src/routes/entity_CRUD/__init__.py

Addresses #362 
Changes
- Ported logic from [HuBMAP PR](https://github.com/hubmapconsortium/ingest-api/pull/543)

Port file system abs path performance improvements

---

src/routes/entity_CRUD/__init__.py

Related PR https://github.com/sennetconsortium/entity-api/pull/363/files

Updating call to PUT Entity API endpoint with new query parameter

---

src/routes/entity_CRUD/__init__.py

Change log:
1. Add check to avoid creating metadata.json for components

Do not create metdata.json when is component - #479

---

docker/docker-compose.development.yml
src/app.py
src/jobs/__init__.py
src/jobs/cache/datasets.py
src/jobs/cache/uploads.py
src/requirements.txt
src/routes/entity_CRUD/__init__.py
src/worker.py

Changes
- Moved data status caching to RQ
- Changed `/datasets/data-status` and `/uploads/data-status` endpoints to read from RQ

Data status endpoints - Issues 611, 612

---

src/lib/services.py

Change log:
1. Remove token from call to `get_associated_sources_from_dataset`

Give None as token default - #622

---

src/instance/app.cfg.example
src/jobs/validation/metadata.py
src/routes/entity_CRUD/__init__.py

Change log:
1. Add check for IVT errors
2. Add `try/except`

Handle response for bad tsv - #633

---

.gitignore
src/jobs/cache/datasets.py

Changes
- Fetched `creation_action` with dataset to determine `is_primary`. This prevents an extra database query for each dataset; similar to HuBMAP.

#664 speed up dataset cache

---

src/instance/app.cfg.example
src/requirements.txt

Change log:
1. Update config
2. Update commons version
AFTER:
Requires https://github.com/x-atlas-consortia/commons/pull/23

Update ubkg config - #665

---

src/jobs/cache/datasets.py

Adding has_source_sample_metadata to data status

---

docker/ingest-api/Dockerfile
src/instance/app.cfg.example
src/requirements.txt
src/routes/status/__init__.py
test/config/app.cfg

Changes
- Added memory and disk usage to status endpoint
- Added psutil to requirements.txt (already used by another library)

Adding memory and storage usage to status endpoint

---

src/routes/status/__init__.py

Changes
- Fixed psutil memory usage in status route

Fixing psutil memory usage in status route

---

src/jobs/cache/datasets.py
src/jobs/cache/uploads.py

Change log:
1. Add error_message fields to response

Add error_message fields - #858
